### ISSUE TITLE
Make the form responsive

### ISSUE THREAD

**Issue by RockySingh137** [RockySingh137/Hacktoberfest2022-HTML-CSS#5]

**Comment by abel-otegbola** [comment]
Hi @RockySingh137 
Can you assign this to me.
Thanks

**Comment by seneenkhan** [comment]
Assign me this

**Comment by RockySingh137** [comment]
> Assign me this

ok

**Comment by hamzailyas237** [comment]
please assign some issue to me.

**Comment by RockySingh137** [comment]
> please assign some issue to me.

will you do firebase authentication of this form?? I will Assign you then

**Comment by hamzailyas237** [comment]
yes i will do firebase authentication

**Comment by RockySingh137** [comment]
> yes i will do firebase authentication

nice

**Comment by hamzailyas237** [comment]
@RockySingh137 I will do firebase auth, but  either in the last or now, you have to give the firebase initialization code, else it will authenticate in my firebase account

**Comment by hamzailyas237** [comment]
If you share your initailization code with me then i will start doing it.

**Comment by RockySingh137** [comment]
> @RockySingh137 I will do firebase auth, but either in the last or now, you have to give the firebase initialization code, else it will authenticate in my firebase account

This website is just a **sample only** ..if you wish you can add your firebase account that will have no issue..

**Comment by hamzailyas237** [comment]
My account is full. Now i can't add any new project.

**Comment by RockySingh137** [comment]
> My account is full. Now i can't add any new project.

ok

**Comment by RockySingh137** [comment]
just write the steps in readme file with title firebase authentication and then create pull request

**Comment by hamzailyas237** [comment]
okay.
